{
    "name": 'Registro Clientes',
    "version": '1.0',
    "author": 'Yenny Delgado',
    "depends": ['base'],
    "category":"Registro Exclusivo para Proveeduria",
    "description":"""Modulo para Registro de DT9 y DT10 Fontur, y Control Interno de Clientes-Organizaciones""",
    "data":['view/registros/reg_vehiculos.xml',
            'view/maestros/reg_tipos_documentos.xml',
            'view/registros/reg_control_documentos.xml',
            'view/registros/reg_respartner.xml',
            'view/maestros/reg_tipos_vehiculos.xml',
            'view/maestros/reg_colores_vehiculos.xml',
            'view/maestros/reg_periodos_renovacion.xml'],
    "demo":[],
    "test":[],
    "installable":True,
    "auto_install":False,
    'css': [ 'static/src/css/stock.css' ],
}
